#include "main.h"

void print_build_flags();

void create_wt_options(wt_parameters_struct &wt){
#include "autogenerated/wt_settings.h"
}

wt_parameters_struct::wt_parameters_struct() {
  create_wt_options(*this);

  simulation_seconds = 10;
  timesteps_per_second = 4000; /*250us*/
  number_datapoints = (timesteps_per_second * simulation_seconds + 1);
  timestep = 1.0 / (double)timesteps_per_second;

  char temporary_path[MAXIMUM_STRING_SIZE];
  unsigned int temp_rows, temp_columns;
  sprintf(temporary_path, "%s/%s", OUTPUT_PATH, "Input.csv");
  read_matrix_csv(temporary_path, &temp_rows, &temp_columns, &Input_Data);
  if (temp_rows != number_datapoints || temp_columns != NUMBER_U_VALUES) {
    abort_msg("Incorrect size of Input  %d   %dx%d\n", number_datapoints,
              temp_rows, temp_columns);
  }

  printf("Parameters: \n");
#ifdef USE_DOUBLE
  printf("IEEE754 type: double\n");
#else
  printf("IEEE754 type: float\n");
#endif
  print_build_flags();

  printf("Simulation seconds: %d s\n", simulation_seconds);
  printf("Integration timestep: %lf us\n",
         1.0e6 / (double)timesteps_per_second);
  printf("Datapoints: %d \n", number_datapoints);
  printf("\n\n\n");
}
